BeaCoach/BeaCoach/Controllers/BeaCoachController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BeaCoach.Controllers
{
    public class BeaCoachController : Controller
    {
        // GET: BeaCoach
        public ActionResult BaeLogin()
        {
            return View();
        }
        public ActionResult BaeProfile()
        {
            return View();
        }

        public ActionResult BaeScopes()
        {
            return View();
        }
        //Open View for Journal
        public ActionResult BaeJournal()
        {
            return View();
        }
        public ActionResult Calender()
        {
            return View();
        }
        //Open View for found Journal
        public ActionResult FindJournalEntry()
        {
            return View();
        }

        //open view for quizzes
        public ActionResult BaeQuizzes()
        {
            return View();
        }

        public ActionResult BaeSignUp()
        {
            return View();
        }
        public ActionResult BaeHome()
        {
            return View();
        }

        public ActionResult UpdateInfo()
        {
            return View();
        }

        public ActionResult DateIdeas()
        {
            return View();
        }

        public ActionResult RomanticDinner()
        {
            return View();
        }
        public ActionResult BaeGifts()
        {
            return View();
        }
        public ActionResult BaeAdvice()
        {
            return View();
        }
        public ActionResult BaeAdviceSingle()
        {
            return View();
        }
        public ActionResult BaeAdviceMarried()
        {
            return View();
        }
        public ActionResult BaeAdviceRelationship()
        {
            return View();
        }
    }
}

BeaCoach/BeaCoach/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BeaCoach.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

BeaCoach/BeaCoach/Views/BeaCoach/BaeAdvice.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>BaeAdvice</title>
    <link href="https://fonts.googleapis.com/css?family=Sofia&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <link href='https://fonts.googleapis.com/css?family=Sofia' rel='stylesheet'>
    <link href="~/Content/AdviceStyleSheet.css" rel="stylesheet" />
</head>
<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Bae Coach</a>
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav">

                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="@Url.Action("BaeHome", "BeaCoach")"><span class="glyphicon glyphicon-menu-hamburger" aria-hidden="true"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="@Url.Action("DateIdeas", "BeaCoach")">Date Ideas</a></li>
                            <li><a href="@Url.Action("BaeScopes", "BeaCoach")">Horoscope</a></li>
                            <li><a href="@Url.Action("BaeJournal", "BeaCoach")">My Journal</a></li>
                            <li><a href="@Url.Action("BaeQuizzes", "BeaCoach")">Quizzes</a></li>
                            <li><a href="@Url.Action("BaeGifts", "BeaCoach")">Gifts</a></li>
                            <li><a href="@Url.Action("BaeAdvice", "BeaCoach")">Advice</a></li>
                            <li><a href="@Url.Action("Calender", "BeaCoach")">Planner</a></li>
                        </ul>
                    </li>
                    <li class="active"><a href="@Url.Action("BaeHome", "BeaCoach")"><span class="glyphicon glyphicon-home" aria-hidden="true"></span></a></li>

                </ul>
                <ul class="nav navbar-nav navbar-right">

                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#"><span class="glyphicon glyphicon-user" aria-hidden="true"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="@Url.Action("BaeProfile", "BeaCoach")"> View User Profile</a></li>
                            <li><a href="@Url.Action("UpdateInfo", "BeaCoach")">Update User Profile</a></li>
                            <li><a href="#">Log Out</a></li>

                        </ul>
                    </li>

                </ul>
            </div>
        </div>
    </nav>
    <h2 class="mainheading"> Advice </h2>
    <div class="selection">
        <h4>
            Please select your relationship status
        </h4><hr /><br />

        <a href="@Url.Action("BaeAdviceSingle", "BeaCoach")">
            Single
        </a>
        <br /><br /><hr /><br />
        <a href="@Url.Action("BaeAdviceRelationship", "BeaCoach")">
            In a relationship
        </a>
        <br /><br /><hr /><br />
        <a href="@Url.Action("BaeAdviceMarried", "BeaCoach")">Married</a>
        <br /><br /><hr />


    </div>
    <div class="image01">
        <img src="http://cd5vo46ju4834fu142zvmudg.wpengine.netdna-cdn.com/wp-content/uploads/Deep-Quotes-About-Love.png"
             style="width:750px;height:390px;border-style:solid; border-width:3px; border-color:black;">

    </div>
</body>
</html>

BeaCoach/BeaCoach/Views/BeaCoach/BaeAdviceMarried.cshtml
@{
                Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="https://fonts.googleapis.com/css?family=Sofia&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <link href='https://fonts.googleapis.com/css?family=Sofia' rel='stylesheet'>
    <link href="~/Content/AdviceStyleSheet.css" rel="stylesheet" />
    <title>BaeAdviceMarried</title>
</head>
<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Bae Coach</a>
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav">

                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="@Url.Action("BaeHome", "BeaCoach")"><span class="glyphicon glyphicon-menu-hamburger" aria-hidden="true"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="@Url.Action("DateIdeas", "BeaCoach")">Date Ideas</a></li>
                            <li><a href="@Url.Action("BaeScopes", "BeaCoach")">Horoscope</a></li>
                            <li><a href="@Url.Action("BaeJournal", "BeaCoach")">My Journal</a></li>
                            <li><a href="@Url.Action("BaeQuizzes", "BeaCoach")">Quizzes</a></li>
                            <li><a href="@Url.Action("BaeGifts", "BeaCoach")">Gifts</a></li>
                            <li><a href="@Url.Action("BaeAdvice", "BeaCoach")">Advice</a></li>
                            <li><a href="@Url.Action("Calender", "BeaCoach")">Planner</a></li>
                        </ul>
                    </li>
                    <li class="active"><a href="@Url.Action("BaeHome", "BeaCoach")"><span class="glyphicon glyphicon-home" aria-hidden="true"></span></a></li>

                </ul>
                <ul class="nav navbar-nav navbar-right">

                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#"><span class="glyphicon glyphicon-user" aria-hidden="true"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="@Url.Action("BaeProfile", "BeaCoach")"> View User Profile</a></li>
                            <li><a href="@Url.Action("UpdateInfo", "BeaCoach")">Update User Profile</a></li>
                            <li><a href="#">Log Out</a></li>

                        </ul>
                    </li>

                </ul>
            </div>
        </div>
    </nav>
    <br />
    <h2 class="mainheading"> Marriage Advice </h2>
    <div class="selection01">
        <img src="https://dz9yg0snnohlc.cloudfront.net/new-what-are-some-cute-marriage-quotes-2.jpg" style="width:400px;height:340px;border-style:solid; border-width:3px; border-color:black;">
    </div>
    <div class="articles01">
        <h4 style="text-decoration:underline;">
            Pointers:
        </h4>
        <p>
            <ul>
                <li>
                    Make sure your partner is your best friend, no matter what.
                </li>
                <li>
                    Don't expect them to read your mind.
                </li>
                <li>
                    At least once a day, try to say something complimentary to your spouse. Gentle words bring life and health!
                </li>
                <li>
                    Remember that criticism and nagging destroy love.
                </li>
                <li>
                    Focus on your spouse’s strengths rather than their weaknesses.
                </li>
            </ul>
        </p>
    </div>

    <div class="footer01">
        <h4 style="text-decoration:underline;">
            Good reads:
        </h4>
        <p>
            Advice From Couples Who’ve Been Married for Decades
            <br />
            Ashley Riddle Williams
            <br />
            <a class="linkAdvice" href="https://www.southernliving.com/healthy-living/marriage-advice">Click here to read...</a>
            <br />
            <br />
            <br />
            25 Pieces Of The Best Marriage Advice Ever
            <br />
            Dave Willis
            <br />
            <a class="linkAdvice" href="https://www.yourtango.com/2015284053/25-pieces-of-best-marriage-advice-ever">Click here to read...</a>
            <br />
            <br />
            <br />
            17 Things Married People Want Newlyweds To Know
            <br />
            Taryn Hillin
            <br />
            <a class="linkAdvice" href="hhttps://www.huffpost.com/entry/marriage-advice_n_5682906?guccounter=1&guce_referrer=aHR0cHM6Ly93d3cuZ29vZ2xlLmNvbS8&guce_referrer_sig=AQAAALkqsXCVGAci4Adot8g_x5xrvnMTEyzTrJ80Z7bg8bI8ULf0I_zjgttXAWq5gEFGfi8pxj9P21O7VMoc7cgPF1PLhlgA8wyQcvAuPcdkJZJaZq3n5Z8NRpgvPx8-2s6Y2AwC6TWNx70bBfL723YAuPfxcRNCOGClmoMPZkoieF4d">Click here to read...</a>
            <br /><br /><br />

        </p>
    </div>
</body>
</html>

BeaCoach/BeaCoach/Views/BeaCoach/BaeAdviceRelationship.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>BaeAdviceRelationship</title>

    <meta name="viewport" content="width=device-width" />
    <link href="https://fonts.googleapis.com/css?family=Sofia&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <link href='https://fonts.googleapis.com/css?family=Sofia' rel='stylesheet'>
    <link href="~/Content/AdviceStyleSheet.css" rel="stylesheet" />
</head>
<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Bae Coach</a>
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav">

                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="@Url.Action("BaeHome", "BeaCoach")"><span class="glyphicon glyphicon-menu-hamburger" aria-hidden="true"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="@Url.Action("DateIdeas", "BeaCoach")">Date Ideas</a></li>
                            <li><a href="@Url.Action("BaeScopes", "BeaCoach")">Horoscope</a></li>
                            <li><a href="@Url.Action("BaeJournal", "BeaCoach")">My Journal</a></li>
                            <li><a href="@Url.Action("BaeQuizzes", "BeaCoach")">Quizzes</a></li>
                            <li><a href="@Url.Action("BaeGifts", "BeaCoach")">Gifts</a></li>
                            <li><a href="@Url.Action("BaeAdvice", "BeaCoach")">Advice</a></li>
                            <li><a href="@Url.Action("Calender", "BeaCoach")">Planner</a></li>
                        </ul>
                    </li>
                    <li class="active"><a href="@Url.Action("BaeHome", "BeaCoach")"><span class="glyphicon glyphicon-home" aria-hidden="true"></span></a></li>

                </ul>
                <ul class="nav navbar-nav navbar-right">

                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#"><span class="glyphicon glyphicon-user" aria-hidden="true"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="@Url.Action("BaeProfile", "BeaCoach")"> View User Profile</a></li>
                            <li><a href="@Url.Action("UpdateInfo", "BeaCoach")">Update User Profile</a></li>
                            <li><a href="#">Log Out</a></li>

                        </ul>
                    </li>

                </ul>
            </div>
        </div>
    </nav>
    <br />
    <h2 class="mainheading"> Relationship Advice </h2>
    <div class="selection01">
        <img src="https://quotefancy.com/media/wallpaper/1600x900/43477-Stephen-R-Covey-Quote-Trust-is-the-glue-of-life-It-s-the-most.jpg" style="width:415px;height:340px;border-style:solid; border-width:3px; border-color:black;">
    </div>
    <div class="articles01">
        <h4 style="text-decoration:underline;">
            Pointers:
        </h4>
        <p>
            <ul>
                <li>
                    Love yourself. Being comfortable with who you are means you'll be a happier partner.
                </li>
                <li>
                    Get over needing to be right.
                </li>
                <li>
                    Assume that if something was said that hurt your feelings, it wasn’t intended that way.

                </li>
                <li>
                    Compliment often.
                </li>
                <li>
                    Take responsibility for your own happiness.
                </li>
            </ul>
        </p>
    </div>

    <div class="footer01">
        <h4 style="text-decoration:underline;">
            Good reads:
        </h4>
        <p>
            The Relationship Advice No One Ever Tells You—But Should
            <br />
            Ashley Papa
            <br />
            <a class="linkAdvice" href="https://stylecaster.com/top-secret-relationship-advice/">Click here to read...</a>
            <br />
            <br />
            <br />
            The Best Relationship Advice, According to Experts
            <br />
            Korin Miller
            <br />
            <a class="linkAdvice" href="https://www.oprahmag.com/life/relationships-love/a25907941/expert-relationship-advice/">Click here to read...</a>
            <br />
            <br />
            <br />
            Express Your Anger Without Pushing Him Away
            <br />
            Rori Raye
            <br />
            <a class="linkAdvice" href="https://www.eharmony.com/dating-advice/relationships/express-your-anger-without-pushing-him-away/">Click here to read...</a>
            <br /><br /><br />

        </p>
    </div>
</body>
</html>

BeaCoach/BeaCoach/Views/BeaCoach/BaeGifts.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>BaeGifts</title>
    <link href="https://fonts.googleapis.com/css?family=Sofia&display=swap" rel="stylesheet">
    <link href="~/Content/GiftsStyleSheet.css" rel="stylesheet" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <link href='https://fonts.googleapis.com/css?family=Sofia' rel='stylesheet'>
</head>
<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Bae Coach</a>
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav">

                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="@Url.Action("BaeHome", "BeaCoach")"><span class="glyphicon glyphicon-menu-hamburger" aria-hidden="true"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="@Url.Action("DateIdeas", "BeaCoach")">Date Ideas</a></li>
                            <li><a href="@Url.Action("BaeScopes", "BeaCoach")">Horoscope</a></li>
                            <li><a href="@Url.Action("BaeJournal", "BeaCoach")">My Journal</a></li>
                            <li><a href="@Url.Action("BaeQuizzes", "BeaCoach")">Quizzes</a></li>
                            <li><a href="@Url.Action("BaeGifts", "BeaCoach")">Gifts</a></li>
                            <li><a href="@Url.Action("BaeAdvice", "BeaCoach")">Advice</a></li>
                            <li><a href="@Url.Action("Calender", "BeaCoach")">Planner</a></li>
                        </ul>
                    </li>
                    <li class="active"><a href="@Url.Action("BaeHome", "BeaCoach")"><span class="glyphicon glyphicon-home" aria-hidden="true"></span></a></li>

                </ul>
                <ul class="nav navbar-nav navbar-right">

                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#"><span class="glyphicon glyphicon-user" aria-hidden="true"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="@Url.Action("BaeProfile", "BeaCoach")"> View User Profile</a></li>
                            <li><a href="@Url.Action("UpdateInfo", "BeaCoach")">Update User Profile</a></li>
                            <li><a href="#">Log Out</a></li>

                        </ul>
                    </li>

                </ul>
            </div>
        </div>
    </nav>
    <br />
    <h2 class="mainheading"> Bae Shop </h2>

    <div class="maindiv">

        <div class="shop">
            <h3>
                Gifts
            </h3>
            <table class="itemsTable">
                @*This will change into a foreach*@
                <tr>

                    <td>
                        <img src="https://m.media-amazon.com/images/I/61gDpmMGvOL._SR500,500_.jpg" alt="KissMug" style="width:140px;height:155px;">
                    </td>
                    <td>
                        <h4>
                            Kissing Mugs Set
                        </h4>
                        <div class="description">

                            These kissing mugs set can be bought for your partner as an anniversary gift. They’re super cute and perfect for the winter months of cuddling up with hot chocolate!
                            <br /><br />
                            Price: R200
                            <br /><br />
                            <input id="purchaseBtn" type="button" value="Click here to purchase" /><br />
                        </div>

                    </td>
                </tr>
                <tr>
                    <td>
                        <img src="https://m.media-amazon.com/images/I/81o4IVaOiLL._AC_UL320_.jpg" alt="Bath Bombs" style="width:140px;height:155px;">

                    </td>
                    <td>

                        <h4>
                            Love Bath Bombs
                        </h4>
                        <div class="description">

                            Treat your loved one with this Little Box of Love Gift Pack containing 6 luxurious Bath Melts.
                            Each product within contains a creamy blend of pure Cocoa and Shea Butters to deeply nourish and hydrate the skin.
                            <br /><br />
                            Price: R120
                            <br /><br />
                            <input id="purchaseBtn" type="button" value="Click here to purchase" /><br />
                        </div>
                    </td>
                <tr>

                    <td>
                        <img src="https://m.media-amazon.com/images/I/91Dmz9Fu2vL._AC_UL320_.jpg" alt="Toilet Paper" style="width:140px;height:155px;">
                    </td>
                    <td>
                        <h4>
                            Maad Romantic Novelty Toilet Paper
                        </h4>
                        <div class="description">


                            Nothing says ‘I love you’ more than giving a sheet! Idea 1st Paper Anniversary Gift, Birthday Present, Christmas Present or Valentine’s Day Gift.
                            Quality bathroom paper with no-smudge ink printing.
                            Hilarious message printed on each sheet!
                            <br /><br />
                            Price: R150
                            <br /><br />
                            <input id="purchaseBtn" type="button" value="Click here to purchase" /><br />
                        </div>

                    </td>
                </tr>
                <tr>
                    <td>
                        <img src="https://m.media-amazon.com/images/I/61xSyLrY-EL._SR500,500_.jpg" alt="Gold Coated Rose" style="width:140px;height:155px;">

                    </td>
                    <td>

                        <h4>
                            Gold Coated Rose
                        </h4>
                        <div class="description">

                            It is made of 100% real beautiful fresh rose, then shaped and retained freshness by resin, you can even see the veins in the petals and leaves. Rose represents love, this gold and not fading rose symbolizes your forever love.
                            <br /><br />
                            Price: R210
                            <br /><br />
                            <input id="purchaseBtn" type="button" value="Click here to purchase" /><br />
                        </div>
                    </td>
                </tr>

            </table>
        </div>
        <div class="shop02">
            <h3>
                Books
            </h3>
            <table class="itemsTable">
                @*This will change into a foreach*@
                <tr>
                    <td>
                        <img src="https://images-na.ssl-images-amazon.com/images/I/51lIOLWv4BL._SX324_BO1,204,203,200_.jpg" alt="This is Going to Hurt-Book" style="width:140px;height:180px;">
                    </td>
                    <td>

                        <h4>
                            This is Going to Hurt: Secret Diaries of a Junior Doctor
                        </h4>
                        <div class="description">

                            ‘Painfully funny. The pain and the funniness somehow add up to something entirely good, entirely noble and entirely loveable.' - Stephen Fry
                            <br /><br />
                            Price: R45
                            <br /><br />
                            <input id="purchaseBtn" type="button" value="Click here to purchase" /><br />
                        </div>

                    </td>
                </tr>
                <tr>

                    <td>
                        <img src="https://images-na.ssl-images-amazon.com/images/I/51p%2BOSddJjL._SX307_BO1,204,203,200_.jpg" alt="Gold Coated Rose" style="width:140px;height:180px;">

                    </td>
                    <td>
                        <h4>
                            A Return to Love: Reflections on the Principles of a "Course in Miracles"
                        </h4>
                        <div class="description">

                            A Return to Love is based on the author’s experiences as a teacher and lecturer on the self-study guide A Course in Miracles. She explains how applying the principles of love to all difficulties can aid in healing and bring about a personal transformation of the reader.
                            <br /><br />
                            Price: R180
                            <br /><br />
                            <input id="purchaseBtn" type="button" value="Click here to purchase" /><br />
                        </div>
                    </td>
                </tr>

                <tr>

                    <td>
                        <img src="https://m.media-amazon.com/images/I/51B5H96bdDL._AC_UL436_.jpg" alt="Bath Bombs" style="width:140px;height:180px;">

                    </td>
                    <td>
                        <h4>
                            Relationships For Dummies
                        </h4>
                        <div class="description">

                            Whether you've just started dating or have been together with that special someone for years, Dr. Kate can help you: tell the difference between a healthy and an unhealthy relationship; have a more loving, fun-filled relationship; enjoy a more vibrant and satisfying sex life; work through most relationship problems; and find the positive and the fun in every relationship stage.
                            <br /><br />
                            Price: R210
                            <br /><br />
                            <input id="purchaseBtn" type="button" value="Click here to purchase" /><br />
                        </div>
                    </td>
                </tr>
            </table>
        </div>

        @*</div>*@
    </div>
</body>
</html>

BeaCoach/BeaCoach/Views/BeaCoach/BaeLogin.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>BaeLogin</title>
    <link href="~/StyleSheet1.css" rel="stylesheet" />
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <link href='https://fonts.googleapis.com/css?family=Sofia' rel='stylesheet'>
    <style>
        label, p {
            color: white;
        }

        body {
            background: rgb(168,29,86);
            background: linear-gradient(to right, rgba(168,29,86,1) 50%, rgba(255,154,154,1) 100%);
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Bae Coach</a>
            </div>
        </div>
    </nav>
    <br />
    <center><h1 style="color:lightpink; font-family: 'Sofia'">Welcome to Bae Coach.</h1></center>
    <br />
    <div style="border-left: 6px solid #ea0a83; border-radius:15px; background-color:lightpink; width:50%;text-align:center; margin:auto">
        <br />
        <table align="center" width:75%;>
            <tr>
                <td style="text-align:left; padding:10px;">Email:</td>
                <td style="text-align:right"><input id="txtEmail" type="text" name="email" /></td>
            </tr>
            <tr>
                <td style="text-align:left; padding:10px;">Password:</td>
                <td style="text-align:right"><input id="txtPassword" type="text" name="password" /></td>
            </tr>
        </table>
        <br />
        @using (Html.BeginForm("BaeHome", "BeaCoach", FormMethod.Get))
        {
        <input id="btnSubmit" type="submit" value="Login" class="buttonLogin" /><br /><br />
        }
    </div>
    <br />
    <div style=" text-align:center">
        <p>Don't have an Account? <a href="@Url.Action("BaeSignUp", "BeaCoach")" style="color:lightpink;">Sign-Up</a></p>
    </div>
</body>
</html>

BeaCoach/BeaCoach/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>